parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                dbname:               ##
                host:                 ##
                port:                 ~
                user:                 ##
                password:             ##
                charset:              ~
                default_table_options:
                    charset:          utf8
                    collate:          utf8
                path:                 ~
                memory:               ~
                unix_socket:          ~
                persistent:           ~
                protocol:             ~
                service:              ~
                sessionMode:          ~
                pooled:               ~
                MultipleActiveResultSets:  ~
                driver:               pdo_pgsql
                platform_service:     ~
                server_version:       ~
                logging:              '%kernel.debug%'
                profiling:            '%kernel.debug%'
                driver_class:         ~
                wrapper_class:        ~
                keep_slave:           false

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App